before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install flake8 pytest

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 pygltflib/__init__.py

pytest:
  stage: Test
  script:
  - pytest test_pygltflib.py