image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis

flake8:
  stage: test
  script:
  - pip3 install flake8
  - flake8 --max-line-length=120 pygltflib/__init__.py

pytest:
  stage: test
  script:
  - pip3 install pytest
  - pytest test_pygltflib.py
